
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ASSIGN COMMA DIV EQ EQUALS GT ID LBRACE LPAREN LT MUL NUMBER PRINT RBRACE RPAREN SEMI STRING SUBprogram : program statement\n| statementstatement : ASSIGN ID EQUALS expression SEMIstatement : PRINT LPAREN expression RPAREN SEMIexpression : expression ADD expression\n| expression SUB expression\n| expression MUL expression\n| expression DIV expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : STRINGexpression : ID'
    
_lr_action_items = {'ASSIGN':([0,1,2,5,21,23,],[3,3,-2,-1,-3,-4,]),'PRINT':([0,1,2,5,21,23,],[4,4,-2,-1,-3,-4,]),'$end':([1,2,5,21,23,],[0,-2,-1,-3,-4,]),'ID':([3,7,8,9,17,18,19,20,],[6,13,13,13,13,13,13,13,]),'LPAREN':([4,7,8,9,17,18,19,20,],[7,9,9,9,9,9,9,9,]),'EQUALS':([6,],[8,]),'NUMBER':([7,8,9,17,18,19,20,],[11,11,11,11,11,11,11,]),'STRING':([7,8,9,17,18,19,20,],[12,12,12,12,12,12,12,]),'RPAREN':([10,11,12,13,15,22,24,25,26,27,],[16,-10,-11,-12,22,-9,-5,-6,-7,-8,]),'ADD':([10,11,12,13,14,15,22,24,25,26,27,],[17,-10,-11,-12,17,17,-9,17,17,17,17,]),'SUB':([10,11,12,13,14,15,22,24,25,26,27,],[18,-10,-11,-12,18,18,-9,18,18,18,18,]),'MUL':([10,11,12,13,14,15,22,24,25,26,27,],[19,-10,-11,-12,19,19,-9,19,19,19,19,]),'DIV':([10,11,12,13,14,15,22,24,25,26,27,],[20,-10,-11,-12,20,20,-9,20,20,20,20,]),'SEMI':([11,12,13,14,16,22,24,25,26,27,],[-10,-11,-12,21,23,-9,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,],[2,5,]),'expression':([7,8,9,17,18,19,20,],[10,14,15,24,25,26,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program statement','program',2,'p_program','parser.py',8),
  ('program -> statement','program',1,'p_program','parser.py',9),
  ('statement -> ASSIGN ID EQUALS expression SEMI','statement',5,'p_statement_assign','parser.py',13),
  ('statement -> PRINT LPAREN expression RPAREN SEMI','statement',5,'p_statement_print','parser.py',17),
  ('expression -> expression ADD expression','expression',3,'p_expression_binop','parser.py',21),
  ('expression -> expression SUB expression','expression',3,'p_expression_binop','parser.py',22),
  ('expression -> expression MUL expression','expression',3,'p_expression_binop','parser.py',23),
  ('expression -> expression DIV expression','expression',3,'p_expression_binop','parser.py',24),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',29),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',33),
  ('expression -> STRING','expression',1,'p_expression_string','parser.py',37),
  ('expression -> ID','expression',1,'p_expression_variable','parser.py',41),
]
